root: true
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2017
extends: "eslint:recommended"
plugins:
  - jasmine
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  no-console: 0
globals:
  proto: readonly
