= mean

[horizontal]
*Invoker*:: Node
*Function*:: link:package.json[package.json]
*Input*:: numbers
*Output*:: mean

=== prerequisites

1. riff is deployed
2. the `riff` CLI is on your PATH
3. the node invoker is installed

   riff invokers apply -f https://github.com/projectriff/node-function-invoker/raw/master/node-invoker.yaml


4. the `topics` helper script is on your PATH
5. the working directory is `samples/mean`

=== create the function and its input topic

```
riff create node --input numbers --output mean --artifact package.json
```

==== make sure that the function is not configured for windowing

Recent builds of the riff CLI configure functions with a windowing size of 1. Check `mean-function.yaml` and comment out the windowing size if necessary.

```yaml
  # windowing:
    # size: 1
```

=== tail the output topic and publish messages

In a terminal window:
```
topics tail -n mean
```
The `topics` script can be found in the root of the [projectriff/riff](https://github.com/projectriff/riff) repo.

In a different terminal window, in quick succession:
```
riff publish --input numbers --data 100
riff publish --input numbers --data 200
riff publish --input numbers --data 0
riff publish --input numbers --data 300
```

If your function is not scaled to zero between events, and assuming no windowing of the input stream, your output should match the following:
```
 Content-Type["text/plain"] 100
 Content-Type["text/plain"] 150
 Content-Type["text/plain"] 100
 Content-Type["text/plain"] 150
```

=== delete the function and its topics

```
riff delete --all
```
